name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - dep/dependency_staging
  schedule:
    - cron: "0 22 * * 1"
jobs:
  build-referee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sudo apt-get -qq update
      - run: sudo apt-get install -y oathtool
      - run: yarn prepare-artifacts
      - name: Slack Notification on Master
        if: ${{ failure() && github.ref == 'refs/heads/master'}}
        uses: rtCamp/action-slack-notify@v2.1.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: referee-alerts
          SLACK_MESSAGE: 'Cerberus main build has failed :build-failed:'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Referee Build Failure Notification
          SLACK_USERNAME: GitHub Actions
